name: Trigger Jenkins Build on PR

# This triggers the action on pull requests
on:
  pull_request:
    types: [opened, synchronize, reopened]  # Events that trigger the action

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Jenkins Build
        run: |
          curl -X POST http://localhost:8080/job/KubeMetricsMonitorPipeline/build \
          --user ${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_TOKEN }}
